files:
  - source: /src/main/resources/assets/randomtech/lang/
    translation: /src/main/resources/assets/randomtech/lang/%locale_with_underscore%.json
  - source: /api/src/main/resources/assets/api/lang/
    translation: /api/src/main/resources/assets/api/lang/%locale_with_underscore%.json
