# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build Mod

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.github/workflows/codeql-analysis.yml'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.github/workflows/codeql-analysis.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build And Publish To Sonatype
      run: ./gradlew publish
      env:
        BINTRAY_GPG_KEY: ${{ secrets.BINTRAY_GPG_KEY }}
        BINTRAY_GPG_PASSWORD: ${{ secrets.BINTRAY_GPG_PASSWORD }}
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }} # Cause for some reason the CurseGradle plugin evaluates here too
      continue-on-error: false
    - name: Upload Compiled Mods to Github Actions For Review
      uses: actions/upload-artifact@v2
      with:
        name: Compiled-Mods
        path: |
          build/libs/*
          api/build/libs/*
    - name: Attempt Close/Release
      run: ls -1 build/libs | grep -q SNAPSHOT && echo `ls -1 api/build/libs | grep -q SNAPSHOT && echo Snapshots Only. Skipping this Step || ./gradlew closeAndReleaseRepository` || ./gradlew closeAndReleaseRepository
      env:
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
    - name: Generate Changelog
      uses: heinrichreimer/github-changelog-generator-action@v2.1.1
      with: # https://github.com/heinrichreimer/action-github-changelog-generator/blob/master/README.md and https://github.com/github-changelog-generator/github-changelog-generator/blob/master/README.md
        token: ${{ secrets.GITHUB_TOKEN }}
        stripGeneratorNotice: true
        verbose: true
        issuesWoLabels: true
        prWoLabels: true
        releaseUrl: https://mvnrepository.com/artifact/me.alexisevelyn
        futureRelease: 0.0.5.7
    - name: Upload Generated Changelog For Review
      uses: actions/upload-artifact@v2
      with:
        name: Generated-Changelog
        path: ${{ github.workspace }}/CHANGELOG.md
    - name: Upload to Curseforge
      run: ls -1 build/libs | grep -q SNAPSHOT && echo `ls -1 api/build/libs | grep -q SNAPSHOT && echo Snapshots Only. Skipping this Step || ./gradlew curseforge` || ./gradlew curseforge
      env:
        CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
        GITHUB_WORKSPACE: ${{ github.workspace }}