# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build Mod

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.github/workflows/codeql-analysis.yml'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.github/workflows/codeql-analysis.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build And Publish To Sonatype
      run: ./gradlew publish
      env:
        BINTRAY_GPG_KEY: ${{ secrets.BINTRAY_GPG_KEY }}
        BINTRAY_GPG_PASSWORD: ${{ secrets.BINTRAY_GPG_PASSWORD }}
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }} # Cause for some reason the CurseGradle plugin evaluates here too
      continue-on-error: false
    - name: Setup Vars For Release Booleans and Version Info
      run: |
        # For Setting Up Independent Release Booleans
        ls -1 build/libs | grep -q SNAPSHOT && echo ::set-env name=RANDOMTECH_RELEASE::false || echo ::set-env name=RANDOMTECH_RELEASE::true
        ls -1 api/build/libs | grep -q SNAPSHOT && echo ::set-env name=API_RELEASE::false || echo ::set-env name=API_RELEASE::true

        # For Setting Up Main Release Boolean
        test "$API_RELEASE" = "true" && echo ::set-env name=RELEASE::true || echo ::set-env name=RELEASE::false
        test "$RANDOMTECH_RELEASE" = "true" && echo ::set-env name=RELEASE::true || echo ::set-env name=RELEASE::false

        # For Setting Up Independent Version Vars
        echo ::set-env name=API_VERSION::$( ls -1 api/build/libs | cut -f3 -d- | awk -F'.jar' '{print $1}' | tail -n1 )
        echo ::set-env name=RANDOMTECH_VERSION::$( ls -1 build/libs | cut -f3 -d- | awk -F'.jar' '{print $1}' | tail -n1 )

        # For Setting Up Main Version Var - Currently Assuming That RandomTech Version is Desired Version Number
        echo ::set-env name=VERSION::$( echo $RANDOMTECH_VERSION )
    - name: Test Result Vars (For Debugging)
      run: |
        echo "Release: '$RELEASE' - API: '$API_RELEASE' - RandomTech: '$RANDOMTECH_RELEASE'"
        echo "Version: '$VERSION' - API: '$API_VERSION' - RandomTech: '$RANDOMTECH_VERSION'"
    - name: Upload Compiled Mods to Github Actions For Review
      uses: actions/upload-artifact@v2
      with:
        name: Compiled-Mods
        path: |
          build/libs/*
          api/build/libs/*
    - name: Update Tag if Release (Testing Only)
      uses: mathieudutour/github-tag-action@v4.5
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        dry_run: true
        default_bump: false
        custom_tag: 0.1.0
    - name: Attempt Close/Release
      if: startsWith(env.RELEASE, 'true')
      run: ./gradlew closeAndReleaseRepository
      env:
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }} # Cause for some reason the CurseGradle plugin evaluates here too
    - name: Generate Changelog
      uses: heinrichreimer/github-changelog-generator-action@v2.1.1
      with: # https://github.com/heinrichreimer/action-github-changelog-generator/blob/master/README.md and https://github.com/github-changelog-generator/github-changelog-generator/blob/master/README.md
        token: ${{ secrets.GITHUB_TOKEN }}
        stripGeneratorNotice: true
        verbose: true
        releaseUrl: https://mvnrepository.com/artifact/me.alexisevelyn
        futureRelease: 0.0.6
        unreleased: true
        issueLineLabels: ALL
    - name: Upload Generated Changelog For Review
      uses: actions/upload-artifact@v2
      with:
        name: Generated-Changelog
        path: ${{ github.workspace }}/CHANGELOG.md
    - name: Upload to Curseforge
      if: startsWith(env.RELEASE, 'true')
      run: ./gradlew curseforge
      env:
        CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
        GITHUB_WORKSPACE: ${{ github.workspace }}